name: Example pipeline
on:
  push:
    branches:
      - main

permissions:
 id-token: write
 contents: read  #This is required for actions/checkout@v2

jobs:
  push:
   runs-on: ubuntu-latest
   steps:
    - name: configureawscredentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
       role-to-assume: arn:aws:iam::282560401657:role/github-ivnc-test
       role-session-name: github-ivnc-test

       aws-region: us-east-1

    - name: Checkout
      uses: actions/checkout@v2
    - name: Terraform Init
      uses: hashicorp/terraform-github-actions/init@v0.4.0
      with:
       role-to-assume: arn:aws:iam::282560401657:role/github-ivnc-test
       role-session-name: github-ivnc-test
       aws-region: us-east-1
      env:
        TF_ACTION_WORKING_DIR: 'Terraform'
    - name: Terraform plan
      uses: hashicorp/terraform-github-actions/validate@v0.3.7
      env:
        TF_ACTION_WORKING_DIR: 'Terraform'
    - name: Terraform Apply
      uses: hashicorp/terraform-github-actions/apply@v0.4.0
      with:
       role-to-assume: arn:aws:iam::282560401657:role/github-ivnc-test
       role-session-name: github-ivnc-test1
       aws-region: us-east-1
      env:
        TF_ACTION_WORKING_DIR: 'Terraform'
        
